# Spring Application Name
spring.application.name=VitalWatch Platform

# Default profile
spring.profiles.default=dev

# Shared Spring DataSource Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Shared Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.naming.physical-strategy=com.vitalwatch.center.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Application Information for Documentation
documentation.application.description=VitalWatch Platform REST API
documentation.application.version=1.0.0
documentation.server.url=${DOCUMENTATION_SERVER_URL:http://localhost:8080}

# JWT Configuration Properties
authorization.jwt.secret=WriteHereYourSecretStringForTokenSigningCredentials
authorization.jwt.expiration.days=7

# i18n message bundles
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Flyway Configuration
spring.flyway.enabled=false
